"""The prototype of the redesign (packages/electro/DESIGN.md): circuits built once, as an immutable
tree; a problem as one is set (given, sought); analyses as pure functions. Beside the library, not
yet in it."""

from .data import problem_from_data, problem_to_data
from .problem import (
    AC,
    DC,
    Across,
    Current,
    I,
    NoSuchParameter,
    NotClosed,
    Parameter,
    Potential,
    Problem,
    Solution,
    Trace,
    U,
    Undetermined,
    V,
    Voltage,
    simulate,
    solve,
)
from .syntax import (
    GND,
    Capacitor,
    Circuit,
    CurrentSource,
    Element,
    ElementTwice,
    Inductor,
    JoinsNodes,
    Kind,
    Net,
    Node,
    Resistor,
    VoltageSource,
    beside,
    cap,
    close,
    cup,
    free,
    is_closed,
    loop,
    netlist,
    parallel,
    series,
    wire,
)

__all__ = [
    "problem_from_data",
    "problem_to_data",
    "AC",
    "Across",
    "beside",
    "cap",
    "Capacitor",
    "Circuit",
    "close",
    "cup",
    "Current",
    "CurrentSource",
    "DC",
    "Element",
    "ElementTwice",
    "free",
    "GND",
    "I",
    "Inductor",
    "is_closed",
    "JoinsNodes",
    "Kind",
    "loop",
    "Net",
    "netlist",
    "Node",
    "NoSuchParameter",
    "NotClosed",
    "parallel",
    "Parameter",
    "Potential",
    "Problem",
    "Resistor",
    "series",
    "simulate",
    "Solution",
    "solve",
    "Trace",
    "U",
    "Undetermined",
    "V",
    "Voltage",
    "VoltageSource",
    "wire",
]
