"""electro — circuits as morphisms of a hypergraph category, with a step-by-step solver.

>>> from electro import *
>>> c = supply(12) + Resistor(10) + Resistor() + ground
>>> sol = c.solve(I_R1=0.5)
>>> sol["R2"].value
14
"""

from sympy import Eq, Symbol, symbols

from .analysis import Relation, Response, Sweep, Thevenin, blackbox, bode, equivalent, resistance, sweep
from .circuit import (
    GROUND,
    Circuit,
    ground,
    join,
    loop,
    net,
    node,
    open_end,
    parallel,
    series,
    shunt,
    spider,
    split,
    swap,
    wire,
    wires,
)
from .codegen import code
from .components import (
    CCCS,
    CCVS,
    VCCS,
    VCVS,
    Ammeter,
    Capacitor,
    Component,
    Coupled,
    CurrentSource,
    Hole,
    Inductor,
    Law,
    Model,
    NoValue,
    OpAmp,
    Resistor,
    Transformer,
    TwoTerminal,
    VoltageSource,
    Voltmeter,
    supply,
)
from .devices import (
    AND,
    DS1307,
    ILI9341,
    LCD1602,
    LCD1602I2C,
    LED,
    NAND,
    NMOS,
    NOR,
    NOT,
    NPN,
    OR,
    PMOS,
    PNP,
    RGBLED,
    SSD1306,
    XOR,
    Arduino,
    Button,
    Buzzer,
    Diode,
    Lamp,
    Motor,
    PassiveBuzzer,
    Photoresistor,
    Pico,
    Potentiometer,
    Relay,
    Servo,
    SevenSegment,
    SineSource,
    SquareSource,
    Switch,
    Thermistor,
    Timer555,
    Ultrasonic,
    Zener,
)
from .issues import Issue
from .sim import Trace, simulate
from .solver import Ambiguous, CircuitError, Contradiction, Diagnosis, I, MissingData, P, Solution, U, V, solve
from .values import fmt, parse

__all__ = [
    "GROUND",
    "Circuit",
    "ground",
    "join",
    "loop",
    "net",
    "node",
    "open_end",
    "parallel",
    "series",
    "shunt",
    "spider",
    "split",
    "swap",
    "wire",
    "wires",
    "CCCS",
    "CCVS",
    "VCCS",
    "VCVS",
    "Ammeter",
    "Capacitor",
    "Component",
    "Coupled",
    "CurrentSource",
    "Hole",
    "Inductor",
    "Law",
    "Model",
    "NoValue",
    "OpAmp",
    "Resistor",
    "Transformer",
    "TwoTerminal",
    "VoltageSource",
    "Voltmeter",
    "supply",
    "Relation",
    "Response",
    "Sweep",
    "Thevenin",
    "blackbox",
    "bode",
    "code",
    "equivalent",
    "resistance",
    "sweep",
    "Ambiguous",
    "CircuitError",
    "Contradiction",
    "Diagnosis",
    "MissingData",
    "I",
    "P",
    "U",
    "V",
    "Solution",
    "solve",
    "fmt",
    "parse",
    "Eq",
    "Symbol",
    "symbols",
    "LED",
    "NMOS",
    "NPN",
    "PMOS",
    "PNP",
    "RGBLED",
    "Arduino",
    "Button",
    "Buzzer",
    "Diode",
    "PassiveBuzzer",
    "Photoresistor",
    "Potentiometer",
    "Servo",
    "SevenSegment",
    "SineSource",
    "SquareSource",
    "Switch",
    "Thermistor",
    "Timer555",
    "Trace",
    "Zener",
    "LCD1602",
    "Ultrasonic",
    "LCD1602I2C",
    "SSD1306",
    "ILI9341",
    "DS1307",
    "Pico",
    "Lamp",
    "Motor",
    "Relay",
    "NOT",
    "AND",
    "NAND",
    "OR",
    "NOR",
    "XOR",
    "Issue",
    "simulate",
]
